### ISSUE TITLE
Flamecord and PaperFlame problem

### ISSUE THREAD

**Issue by Strxnik** [HSGamer/MCServerUpdater#2]
I tried to download FlameCord and FlamePaper but it gave me an error:
`[INFO] Start updating...
java.io.FileNotFoundException: https://ci.2lstudios.dev/job/FlamePaper/api/json?tree=lastSuccessfulBuild[number]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at me.hsgamer.mcserverupdater.api.JenkinsUpdater.getLatestBuild(JenkinsUpdater.java:60)
        at me.hsgamer.mcserverupdater.UpdateBuilder.lambda$executeAsync$4(UpdateBuilder.java:138)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at me.hsgamer.mcserverupdater.UpdateBuilder.executeAsync(UpdateBuilder.java:126)
        at me.hsgamer.mcserverupdater.UpdateBuilder.execute(UpdateBuilder.java:173)
        at me.hsgamer.mcserverupdater.MCServerUpdater.main(MCServerUpdater.java:74)
[SEVERE] Failed to update
java.lang.Exception: No build found
        at me.hsgamer.mcserverupdater.UpdateStatus.<init>(UpdateStatus.java:46)
        at me.hsgamer.mcserverupdater.UpdateStatus.<clinit>(UpdateStatus.java:18)
        at me.hsgamer.mcserverupdater.UpdateBuilder.lambda$executeAsync$4(UpdateBuilder.java:141)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at me.hsgamer.mcserverupdater.UpdateBuilder.executeAsync(UpdateBuilder.java:126)
        at me.hsgamer.mcserverupdater.UpdateBuilder.execute(UpdateBuilder.java:173)
        at me.hsgamer.mcserverupdater.MCServerUpdater.main(MCServerUpdater.java:74)`

**Comment by HSGamer** [comment]
They removed them from the download site, so this is not my problem.
Either compile the source code on your own or buy their copy.
